### ISSUE TITLE
no permissions for notes db

### ISSUE THREAD

**Issue by maxandersen** [HamburgChimps/apple-notes-liberator#14]
when I run I get:

"Cannot copy notes database, do you have read and execute permissions for /Users/myuser/Library/Group Containers/group.com.apple.notes/notestore.sqlite"

and I can't see how to even copy/modify the permissions to try using another file.

Any tips for how to get it copied?

**Comment by alexkolson** [comment]
Hey @maxandersen! Sorry this is happening! Thanks for opening an issue. Hmm...if the file is there, you could try copying it yourself and then pass `-f path/to/copy.sqlite` on the command line. I have a relatively older mac, maybe apple changed the permissions for that file in newer versions?

**Comment by maxandersen** [comment]
Yeah so I tried that and no dice. Even with sudo I get permission error which is surprising :/

**Comment by alexkolson** [comment]
Well shoot. Thanks for your patience! If it doesn't work with sudo I highly doubt it is a permissions issue, but rather some other error is happening and my error message is wrong. I'll release a version that creates a debug log with a flag and post here when its released. I'd be really interested to see what's going wrong/what my program is doing wrong here.

**Comment by apoland** [comment]
I'm seeing a similar issue.  MacOS has some extended protection on this folder that I don't understand.  I can manage to list the database file but it thwarts attempts to read the file or list the contents of the directory:

```
> sudo ls -la "/Users/apoland/Library/Group Containers/group.com.apple.notes/"
total 0
ls: /Users/apoland/Library/Group Containers/group.com.apple.notes/: Operation not permitted

> sudo ls -la "/Users/apoland/Library/Group Containers/group.com.apple.notes/notestore.sqlite"
Password:
-rw-r--r--@ 1 apoland  staff  917504 Mar 27 15:35 /Users/apoland/Library/Group Containers/group.com.apple.notes/notestore.sqlite

> sudo cp "/Users/apoland/Library/Group Containers/group.com.apple.notes/notestore.sqlite" .
Password:
cp: /Users/apoland/Library/Group Containers/group.com.apple.notes/notestore.sqlite: Operation not permitted
```

**Comment by jiwon79** [comment]
Are you using an external program like Iterm? I use iterm, but I have a problem because I don't have permission to access folders in iterm. So adding "full disk access" to Mac settings fixed the issue. You can enable full disk access by referring to the link below

https://kb.synology.com/en-us/C2/tutorial/How_to_enable_Full_Disk_Access_on_a_Mac

**Comment by apoland** [comment]
> Are you using an external program like Iterm? I use iterm, but I have a problem because I don't have permission to access folders in iterm. So adding "full disk access" to Mac settings fixed the issue. You can enable full disk access by referring to the link below
> 
> https://kb.synology.com/en-us/C2/tutorial/How_to_enable_Full_Disk_Access_on_a_Mac

Thanks that fixed it for me!

**Comment by alexkolson** [comment]
Hey cool that this fixed your issue @apoland! @jiwon79 if you want to open a PR with these instructions in the readme I will totally accept it! Thank you so much! Otherwise I’ll add it myself but be sure to credit you.

@maxandersen If you are comfortable with it, could you try @jiwon79’s suggestion and see if it helps in your case?

Still planning on releasing a version with debug logging but curious if enabling extended permissions works for you

**Comment by maxandersen** [comment]
thanks all - the full disk access was the magic trick I needed!

awesome :)
