### ISSUE TITLE
Update application version in nix shell

### ISSUE THREAD

**Issue by alexkolson** [HamburgChimps/apple-notes-liberator#33]
Hey @adam-fallon, would you mind helping here? :)

I am happy to do it as well, but I am not sure how exactly the sha256 hash is being generated/what is being hashed. When I use `openssl` to generate a sha256 hash for the 1.1.0 jar it is nothing like the one in `nix.shell`. Any tips you could share?

Thank you!

**Comment by adam-fallon** [comment]
Sure thing [here is the PR](https://github.com/HamburgChimps/apple-notes-liberator/pull/34). 

So for background, the reason you can't generate the hash from the zip file is, the hash used in the shell.nix is the hash of the contents of all the files when downloaded and extracted inside the nix-store. Sometimes this is referred to as the [nix-hash](https://nixos.wiki/wiki/Nix_Hash). 

So, for clarity - `the sha256 is the hash of the output of the derivation in the nix-store of this file being downloaded and extracted NOT the hash of the file.`

The reason for this is to for safety against collision attacks where someone generates two zips with different files, but the same hash - nix would catch this kind of attack, normal file hashing wouldn't. This is a difficult attack to pull off, but in the future it might not be so hard to pull off.

It's explained here;
-

There is a tool to compute the hash;
- https://www.mankier.com/1/nix-hash

Another thing you can do is use a built in util to fake the hash;
<img width="1512" alt="Screenshot 2023-04-13 at 22 13 26" src="https://user-images.githubusercontent.com/103489648/231884153-456a7729-89b9-4fbb-b2a8-b2bec267751a.png">

Which will generate the following error telling you the right hash;
<img width="1512" alt="Screenshot 2023-04-13 at 22 14 22" src="https://user-images.githubusercontent.com/103489648/231884260-9a15651d-e0d9-4da7-9252-eb263cc9c3bb.png">

And here is the hash for the 2.0.0 release.

Does that make sense? I avoided explaining this in the initial PR because its a bit of a quirk of nix, but the underlining point is - it's for security.

**Comment by adam-fallon** [comment]
Another link explaining the (very understandable!) confusion between what the hash is actually hashing can be found here; https://ryantm.github.io/nixpkgs/builders/fetchers/

**Comment by alexkolson** [comment]
Thank you a ton for the background information and the PR! Merged.
